
import { Metadata } from "next";
import { ItemsContent } from "./ItemsContent"
import { searchService } from "@/services/search.service"

type Props = {
    search: string
}

export const metadata: Metadata = {
    title: "Aca cambio esto",
    description: "Generated by create next app",
  };

export const ItemsWrapper = async ({search}:Props) => {
    const listProductsResponse  = await searchService.search(search);
    return (<>
        <ItemsContent responseListProduts={listProductsResponse}  />
    </>)
}