import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/styles/theme.scss";
import { Header } from "@/components/layout/header/Header";
import Content from "@/components/layout/content/Content";

const inter = Roboto({
  weight: ['400', '500', '700'],
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Prueba Meli",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Header />
        <Content>{children}</Content>
      </body>
    </html>
  );
}
